### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by dronecz** [hunsalz/log4Esp#1]
Hi @hunsalz 

thanks for really nice library, but do you plan to make support for ESP32? 

I tryed to modify you library, but I don´t have enough skills to do it. 

Thx

**Comment by hunsalz** [comment]
Hi @dronecz,

thx for your interest. 

So far I didn't use ESP32 in my own projects. I plan to use ESP32 as well, but time is usually limited ... Until now I had no time to test ESP32 myself, so that I'm not aware what needs to be changed.

I appreciate, if you can provide a stacktrace or precise your question(s). Maybe I can give you some hints, how to modify the sources yourself.

**Comment by jaygreco** [comment]
I just added a PR (#4) for ESP32 support if this is still of interest.
